/**
 * 카테고리별 키워드 풀
 * 네이버 트렌드 API로 순위를 매긴 후 가장 인기 있는 키워드로 포스팅
 */

export const KEYWORD_POOL: Record<string, { keyword: string; slug: string }[]> = {
  electronics: [
    { keyword: '무선 이어폰 추천', slug: 'wireless-earbuds' },
    { keyword: '블루투스 스피커 추천', slug: 'bluetooth-speaker' },
    { keyword: '노트북 거치대 추천', slug: 'laptop-stand' },
    { keyword: '기계식 키보드 추천', slug: 'mechanical-keyboard' },
    { keyword: '무선 마우스 추천', slug: 'wireless-mouse' },
    { keyword: '27인치 모니터 추천', slug: '27inch-monitor' },
    { keyword: '웹캠 추천', slug: 'webcam' },
    { keyword: '외장하드 추천', slug: 'external-hdd' },
    { keyword: 'USB 허브 추천', slug: 'usb-hub' },
    { keyword: '멀티탭 추천', slug: 'power-strip' },
    { keyword: '공기청정기 추천', slug: 'air-purifier' },
    { keyword: '로봇청소기 추천', slug: 'robot-vacuum' },
    { keyword: '무선충전기 추천', slug: 'wireless-charger' },
    { keyword: '보조배터리 추천', slug: 'power-bank' },
    { keyword: '태블릿 거치대 추천', slug: 'tablet-stand' },
    { keyword: '게이밍 헤드셋 추천', slug: 'gaming-headset' },
    { keyword: 'LED 데스크램프 추천', slug: 'led-desk-lamp' },
    { keyword: '전동 드라이버 추천', slug: 'electric-driver' },
    { keyword: 'NAS 추천 가정용', slug: 'home-nas' },
    { keyword: '스마트워치 추천', slug: 'smartwatch' },
    { keyword: '에어컨 추천', slug: 'air-conditioner' },
    { keyword: '선풍기 추천', slug: 'fan' },
    { keyword: '제습기 추천', slug: 'dehumidifier' },
    { keyword: '가습기 추천', slug: 'humidifier' },
    { keyword: '전기장판 추천', slug: 'electric-blanket' },
    { keyword: '온풍기 추천', slug: 'heater' },
    { keyword: '공기순환기 추천', slug: 'air-circulator' },
    { keyword: '음식물처리기 추천', slug: 'food-waste-disposer' },
    { keyword: '건조기 추천', slug: 'dryer' },
    { keyword: '식기세척기 추천', slug: 'dishwasher' },
    { keyword: '전자레인지 추천', slug: 'microwave' },
    { keyword: '에어프라이어 추천', slug: 'air-fryer' },
    { keyword: '무선청소기 추천', slug: 'cordless-vacuum' },
    { keyword: '노이즈캔슬링 헤드폰 추천', slug: 'anc-headphone' },
    { keyword: '미니빔프로젝터 추천', slug: 'mini-projector' },
    { keyword: '전기포트 추천', slug: 'electric-kettle' },
    { keyword: '안마의자 추천', slug: 'massage-chair' },
    { keyword: '전동칫솔 추천', slug: 'electric-toothbrush' },
    { keyword: '헤어드라이기 추천', slug: 'hair-dryer' },
    { keyword: '고데기 추천', slug: 'hair-iron' },
  ],
  'car-accessories': [
    { keyword: '차량용 공기청정기 추천', slug: 'car-air-purifier' },
    { keyword: '블랙박스 추천', slug: 'dashcam' },
    { keyword: '차량용 핸드폰 거치대 추천', slug: 'car-phone-mount' },
    { keyword: '차량용 무선충전기 추천', slug: 'car-wireless-charger' },
    { keyword: '차량용 방향제 추천', slug: 'car-air-freshener' },
    { keyword: '자동차 시트커버 추천', slug: 'car-seat-cover' },
    { keyword: '차량용 청소기 추천', slug: 'car-vacuum' },
    { keyword: '점프스타터 추천', slug: 'jump-starter' },
    { keyword: '타이어 공기압 충전기 추천', slug: 'tire-inflator' },
    { keyword: '차량용 냉온컵홀더 추천', slug: 'car-cup-cooler' },
    { keyword: '자동차 선팅 필름 추천', slug: 'car-tint-film' },
    { keyword: '트렁크 정리함 추천', slug: 'trunk-organizer' },
    { keyword: '차량용 인버터 추천', slug: 'car-inverter' },
    { keyword: '후방카메라 추천', slug: 'rear-camera' },
    { keyword: '자동차 코팅제 추천', slug: 'car-coating' },
    { keyword: '와이퍼 추천', slug: 'wiper-blade' },
    { keyword: '차량용 LED 전구 추천', slug: 'car-led-bulb' },
    { keyword: '자동차 매트 추천', slug: 'car-floor-mat' },
    { keyword: '대시보드 캠 추천', slug: 'dashboard-cam' },
    { keyword: '차량 방충망 추천', slug: 'car-mosquito-net' },
    { keyword: '차량용 선풍기 추천', slug: 'car-fan' },
    { keyword: '차량용 냉장고 추천', slug: 'car-fridge' },
    { keyword: '자동차 세차용품 추천', slug: 'car-wash-supplies' },
    { keyword: '차량용 햇빛가리개 추천', slug: 'car-sunshade' },
    { keyword: '차박 매트 추천', slug: 'car-camping-mat' },
    { keyword: '자동차 방석 추천', slug: 'car-cushion' },
    { keyword: '차량용 가습기 추천', slug: 'car-humidifier' },
    { keyword: '스노우체인 추천', slug: 'snow-chain' },
    { keyword: '자동차 배터리 충전기 추천', slug: 'car-battery-charger' },
    { keyword: '차량용 테이블 추천', slug: 'car-table' },
  ],
  'camping-outdoor': [
    { keyword: '캠핑의자 추천', slug: 'camping-chair' },
    { keyword: '캠핑 텐트 추천', slug: 'camping-tent' },
    { keyword: '캠핑 침낭 추천', slug: 'sleeping-bag' },
    { keyword: '캠핑 랜턴 추천', slug: 'camping-lantern' },
    { keyword: '캠핑 테이블 추천', slug: 'camping-table' },
    { keyword: '캠핑 버너 추천', slug: 'camping-burner' },
    { keyword: '아이스박스 추천', slug: 'ice-cooler' },
    { keyword: '캠핑 매트 추천', slug: 'camping-mat' },
    { keyword: '등산화 추천', slug: 'hiking-shoes' },
    { keyword: '등산 배낭 추천', slug: 'hiking-backpack' },
    { keyword: '캠핑 코펠 세트 추천', slug: 'camping-cookware' },
    { keyword: '캠핑 타프 추천', slug: 'camping-tarp' },
    { keyword: '화로대 추천', slug: 'fire-pit' },
    { keyword: '감성캠핑 소품 추천', slug: 'camping-decor' },
    { keyword: '캠핑 우드 선반 추천', slug: 'camping-wood-shelf' },
    { keyword: '보온병 추천', slug: 'thermos-bottle' },
    { keyword: '등산 스틱 추천', slug: 'trekking-pole' },
    { keyword: '캠핑 그릴 추천', slug: 'camping-grill' },
    { keyword: '방수 자켓 추천', slug: 'waterproof-jacket' },
    { keyword: '캠핑 전기장판 추천', slug: 'camping-heating-pad' },
    { keyword: '캠핑 감성 조명 추천', slug: 'camping-mood-light' },
    { keyword: '경량 캠핑의자 추천', slug: 'lightweight-camping-chair' },
    { keyword: '백패킹 텐트 추천', slug: 'backpacking-tent' },
    { keyword: '캠핑 커피 세트 추천', slug: 'camping-coffee-set' },
    { keyword: '차박 텐트 추천', slug: 'car-camping-tent' },
    { keyword: '캠핑 선풍기 추천', slug: 'camping-fan' },
    { keyword: '캠핑 난로 추천', slug: 'camping-stove-heater' },
    { keyword: '피크닉 매트 추천', slug: 'picnic-mat' },
    { keyword: '낚시의자 추천', slug: 'fishing-chair' },
    { keyword: '쿨러백 추천', slug: 'cooler-bag' },
  ],
};
